### ISSUE TITLE
Problem with series-parallel composition

### ISSUE THREAD

**Issue by jsmith173** [ufkapano/graphtheory#11]
Hi,

I'm trying to use the series parallel composition to calculate the total resistance in a simple electronics circuits. I have many circuits for that the total resistance is calculated good however the following case calculated wrong. Is there any workaround?

Python code:
```
from graphtheory.structures.edges import Edge
from graphtheory.structures.graphs import Graph
from graphtheory.structures.factory import GraphFactory
from graphtheory.seriesparallel.sptrees import find_sptree
from graphtheory.seriesparallel.spnodes import btree_print

#
N = 6           # number of nodes
G = Graph(N)
nodes = range(N)
edges = [Edge(1, 2), Edge(2, 3), Edge(3, 0), Edge(2, 4), Edge(4, 0), Edge(4, 5), Edge(5, 0)]
for node in nodes:
 G.add_node(node)
for edge in edges:
 G.add_edge(edge)

#
T = find_sptree(G)
btree_print(T)
```

The output (with my notes)

```
R6 1 2
R5 2 3
R4 3 0
R3 2 4
R2 4 0
R1 4 5
<split> 5 0

   [1]Node(1, 2, 'edge') R6
      [2]Node(2, 4, 'edge') R3
            [4]Node(2, 3, 'edge') R5
            [4]Node(3, 0, 'edge') R4
         [3]Node(2, 0, 'series') R5+R4=Ra
            [4]Node(0, 4, 'edge') R2
               [5]Node(0, 5, 'edge') <split>
               [5]Node(5, 4, 'edge') R1
            [4]Node(0, 4, 'series') R1
         [3]Node(0, 4, 'parallel') R2|R1=Rb
      [2]Node(2, 4, 'series') Ra+Rb WRONG!
   [1]Node(2, 4, 'parallel') WRONG: R3 not parallel
[0]Node(1, 4, 'series')


{'value': 1.75, 'valid': True, 'expected': 2.0, 'circuit_key': 'circuit_no_gens'}
fn: g-ser-par2-ok.json, Solver error: error
```

Here is the circuit:
Generator is not in the graph. We can't have parallel edges so R1 is splitted by a dummy edge (<split>)
![circ err](https://github.com/ufkapano/graphtheory/assets/10882689/fb35550c-9677-4bd6-a065-8533d947e876)

**Comment by ufkapano** [comment]
Hello,

Recognizing an undirected sp-graph is not unique and this is your case. The tree found by the program is correct but you expected a different solution. 

In your case (electronics circuits), the starting node (1) and the ending node (0) are known, so I suggest using directed series-parallel graphs. I added new modules (dsptools, dsptrees) and tester files with examples. The file tester2.py returns your expected solution.

Regards,
Andrzej
